### ISSUE TITLE
Regarding Hacktoberfest 2020

### ISSUE THREAD

**Issue by crpoudyal** [Hacktoberfest-Nepal/Your-First-PR#1]
Is our PR is counted if we PR only in the month of Oct?

**Comment by Aju100** [comment]
@crpoudyal  yes. right now please let us create proper guidelines and material for it. And register our event in the README docs. And it will be counted in the month of Oct.

**Comment by crpoudyal** [comment]
ok Thank you for your response

**Comment by Aju100** [comment]
@crpoudyal  good to know from you. Make sure you share it to your friends.

**Comment by Aju100** [comment]
@crpoudyal  hello. you can create PR hae
