### ISSUE TITLE
Update the README.md for timeline and refactor the documentation

### ISSUE THREAD

**Issue by Aju100** [Hacktoberfest-Nepal/Your-First-PR#114]

**Comment by washbin** [comment]
should the [CONTRIBUTORS.md](https://github.com/Hacktoberfest-Nepal/Your-First-PR/blob/master/CONTRIBUTORS.md) file also be reset ?
Or is updating the documentation links/resources and the image enough ?

**Comment by Aju100** [comment]
@washbin remove the CONTRIBUTORS.md, also we won't the audience just to make a PR via adding name

**Comment by Bibekdhkl** [comment]
@Aju100 Isn't it fine to just override the existing content on the CONTRIBUTORS.md?

**Comment by Bibekdhkl** [comment]
I guess It will also be good if we Archive previous year's Hacktoberfest rather than removing if that's possible in any way so that if anyone who is willing can also see what has happened last year!

**Comment by Aju100** [comment]
@Bibekdhkl @washbin sure guys work on ek jana, we can override this file aru audience ko lagi

**Comment by washbin** [comment]
@Aju100 @Bibekdhkl  see if pull request #115 works for this issue
