### ISSUE TITLE
Hacktoberfest 2020

### ISSUE THREAD

**Issue by Aju100** [Hacktoberfest-Nepal/Your-First-PR#28]
## Hacktoberfest 2020

Anyone interested to send your PR is very welcome. Add your name with the GitHub profile link, info and you are done.

Please check the [README docs](https://github.com/Hacktoberfest-Nepal/Your-First-PR).

If you have any confusion, feel free to ask in comment.

**Comment by shivarajloni** [comment]
hey can i contribute

**Comment by beertocode** [comment]
Please assign me this issue.

**Comment by Aju100** [comment]
@shivarajloni  @beertocode  sure
