### ISSUE TITLE
Make your first PR

### ISSUE THREAD

**Issue by Aju100** [Hacktoberfest-Nepal/Your-First-PR#3]
Hello hackers,

Don't you wanna start your journey in Opensource. If so, what are you waiting for, forked, clone, and register your info in Your-First-PR? Create a Pull Request and we will merge it. Make sure your name and info are sorted. Thank you

**Comment by nimeshkavinda** [comment]
Hi, I want to remove my contributions to this repo. @Aju100 could you please remove my commit? Thanks a lot!

**Comment by Aju100** [comment]
@nimeshkavinda  sure i will remove it.

**Comment by nimeshkavinda** [comment]
> @nimeshkavinda sure i will remove it.

Thanks a lot!
