### ISSUE TITLE
sort contributor name list alphabetically

### ISSUE THREAD

**Issue by Aju100** [Hacktoberfest-Nepal/Your-First-PR#44]
hello hacker, 

we have a bunch of PR and lots of them have been merge without sorted. In order to solve it, you can sort listed our contributor's name list and send a PR . we would happy to merge your PR and contribution.

**Comment by Tusharr08** [comment]
Okay ! sure, I will do that.

**Comment by Aju100** [comment]
@Tusharr08  sure

**Comment by InfamousBolt** [comment]
Is it still open? May I do it?

**Comment by Tusharr08** [comment]
It isn't worth it ...somebody had reported this repository and so it's pull request is not counted in Hacktober fest

**Comment by InfamousBolt** [comment]
Oh shoot!
